Hackathon/Controllers/MentalHealthAssesmentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace Hackathon.Controllers
{
    public class MentalHealthAssesmentController : Controller
    {
       
        public IActionResult RoutineAssesment()
        {
            return View();
        }

        public IActionResult SleepDisorderAssesment()
        {
            return View();
        }

        public IActionResult AnxietyAssesment()
        {
            return View();
        }

        public IActionResult StressAssesment()
        {
            return View();
        }


        public IActionResult DepressionAssesment()
        {
            return View();
        }
    }
}

Hackathon/Controllers/UnderProcessController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace Hackathon.Controllers
{
    public class UnderProcessController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Hackathon/Views/MentalHealthAssesment/AnxietyAssesment.cshtml
@{
    ViewData["Title"] = "AnxietyAssesment";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1  style="color:darkgoldenrod">Anxiety Assesment</h1>
<table style="color:darkgoldenrod">
    <tr>
        <td>Do you feel lonely at times?</td>
    </tr>
    <tr>
        <td>Yes @Html.RadioButton("lonely", "Yes")&nbsp;&nbsp;&nbsp;&nbsp;No @Html.RadioButton("lonely", "NO")&nbsp;&nbsp;&nbsp;&nbsp;</td>
    </tr>
    <tr>
        <td>  Do you have a worry which interferes with your daily life activities?</td>
    </tr>
    <tr>
        <td>Yes @Html.RadioButton("worry", "Yes")&nbsp;&nbsp;&nbsp;&nbsp; No @Html.RadioButton("worry", "No")&nbsp;&nbsp;&nbsp;&nbsp;</td>
    </tr>
    <tr>
        <td>Do you have any OCD (Obsessive Compulsive Disorder)? </td>
    </tr>
    <tr>
        <td>Yes @Html.RadioButton("ocd", "Yes")&nbsp;&nbsp;&nbsp;&nbsp; No @Html.RadioButton("ocd", "No")&nbsp;&nbsp;&nbsp;&nbsp;</td>
    </tr>
    <tr>
        <td>Do feelings of anxiety or discomfort around others bother you? </td>
    </tr>
    <tr>
        <td>Yes @Html.RadioButton("discomfort", "Yes")&nbsp;&nbsp;&nbsp;&nbsp; No @Html.RadioButton("discomfort", "No")&nbsp;&nbsp;&nbsp;&nbsp;</td>
    </tr>
    <tr>
        <td>Do you have any kind of fear which reaches at its peak within minutes? </td>
    </tr>
    <tr>
        <td>
            Yes @Html.RadioButton("fear", "Yes")&nbsp;&nbsp;&nbsp;&nbsp; No @Html.RadioButton("fear", "No")&nbsp;&nbsp;&nbsp;&nbsp;
        </td>
    </tr>
    <tr>
        <td>
            <input  class="btn btn-info" style="color:darkgoldenrod;background-color:white;" value="Submit" id="btnSubmit" onclick="location.href='@Url.Action("Index", "UnderProcess")'">
        </td>
    </tr>
</table>

Hackathon/Views/MentalHealthAssesment/DepressionAssesment.cshtml
@{
    ViewData["Title"] = "DepressionAssesment";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1  style="color:darkgoldenrod">Depression  Assesment</h1>
<table style="color:darkgoldenrod">
    <tr>
        <td>
            Do you feel sad or hopeless?
        </td>
           
    </tr>
    <tr>
        <td>Yes @Html.RadioButton("hopeless", "Yes")&nbsp;&nbsp;&nbsp;&nbsp; No @Html.RadioButton("hopeless", "No")&nbsp;&nbsp;&nbsp;&nbsp;</td>
    </tr>
    <tr>
        <td>Have you lost interest in most of your daily chores?</td>
    </tr>
    <tr>
        <td> Yes @Html.RadioButton("lossofinterest", "Yes")&nbsp;&nbsp;&nbsp;&nbsp; No @Html.RadioButton("lossofinterest", "No")&nbsp;&nbsp;&nbsp;&nbsp;</td>
    </tr>
    <tr>
        <td>Have you lost OR gained weight suddenly?</td>
    </tr>
    <tr>
        <td>Yes @Html.RadioButton("weight", "Yes")&nbsp;&nbsp;&nbsp;&nbsp; No @Html.RadioButton("weight", "No")&nbsp;&nbsp;&nbsp;&nbsp;</td>
    </tr>
    <tr>
        <td>Have you recently started too much binge eating?</td>
    </tr>
    <tr>
        <td>Yes @Html.RadioButton("bingeeating", "Yes")&nbsp;&nbsp;&nbsp;&nbsp; No @Html.RadioButton("bingeeating", "No")&nbsp;&nbsp;&nbsp;&nbsp;</td>
    </tr>
    <tr>
        <td>Have you recently lost your appetite by more than 70%-80%?</td>
    </tr>
    <tr>
        <td>Yes @Html.RadioButton("lossofappetite", "Yes")&nbsp;&nbsp;&nbsp;&nbsp; No @Html.RadioButton("lossofappetite", "No")&nbsp;&nbsp;&nbsp;&nbsp;</td>
    </tr>
    <tr>
        <td>Do you feel restless and/or are unable to sit still?</td>
    </tr>
    <tr>
        <td>Yes @Html.RadioButton("sitstill", "Yes")&nbsp;&nbsp;&nbsp;&nbsp; No @Html.RadioButton("sitstill", "No")&nbsp;&nbsp;&nbsp;&nbsp;</td>
    </tr>
    <tr>
        <td>Do you feel unworthy and/or guilty every other day?</td>
    </tr>
    <tr>
        <td>Yes @Html.RadioButton("guilt", "Yes")&nbsp;&nbsp;&nbsp;&nbsp; No @Html.RadioButton("guilt", "No")&nbsp;&nbsp;&nbsp;&nbsp;</td>
    </tr>
    <tr>
        <td>Have you experienced a week or longer of lower-than-usual interest in activities that you usually enjoy? Examples might include work, exercise, or hobbies.</td>
    </tr>
    <tr>
        <td>Yes @Html.RadioButton("lowintrestinhobbies", "Yes")&nbsp;&nbsp;&nbsp;&nbsp; No @Html.RadioButton("lowintrestinhobbies", "No")&nbsp;&nbsp;&nbsp;&nbsp;</td>
    </tr>
    <tr>
        <td>Do you find it hard to focus, remember things, or make decisions quite often?</td>
    </tr>
    <tr>
        <td>
            Yes @Html.RadioButton("hardtofocus", "Yes")&nbsp;&nbsp;&nbsp;&nbsp; No @Html.RadioButton("hardtofocus", "No")&nbsp;&nbsp;&nbsp;&nbsp;
        </td>
    </tr>
    <tr>
        <td>  <input  class="btn btn-info" style="color:darkgoldenrod;background-color:white;" value="Submit" id="btnSubmit"   onclick="location.href='@Url.Action("Index", "UnderProcess")'"></td>
    </tr>
</table>

Hackathon/Views/MentalHealthAssesment/RoutineAssesment.cshtml
@{
    ViewData["Title"] = "RoutineAssesment";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1 style="color:darkgoldenrod">Routine  Assesment</h1>
<table style="color:darkgoldenrod">
    <tr>
        <td>How are you feeling today?</td>
    </tr>
    <tr>
        <td>Happy @Html.RadioButton("Feeling", "Happy")&nbsp;&nbsp;&nbsp;&nbsp;  Sad @Html.RadioButton("Feeling", "Sad")&nbsp;&nbsp;&nbsp;&nbsp;Angry @Html.RadioButton("Feeling", "Angry")&nbsp;&nbsp;&nbsp;&nbsp;Neutral @Html.RadioButton("Feeling", "Neutral")&nbsp;&nbsp;&nbsp;&nbsp;</td>
    </tr>

    <tr>
        <td>Do you often feel this way?</td>
    </tr>
    <tr>
        <td> Yes @Html.RadioButton("FeelingOften", "Yes")&nbsp;&nbsp;&nbsp;&nbsp;  No @Html.RadioButton("FeelingOften", "No")&nbsp;&nbsp;&nbsp;&nbsp;</td>
    </tr>

    <tr>
        <td>  How often this happens to you?</td>
    </tr>

    <tr>
        <td>Once In a While @Html.RadioButton("FeelingFrequency", "While")&nbsp;&nbsp;&nbsp;&nbsp;Once In a Week @Html.RadioButton("FeelingFrequency", "Week")&nbsp;&nbsp;&nbsp;&nbsp;Once In a Month @Html.RadioButton("FeelingFrequency", "Month")  </td>
    </tr>

    <tr>
        <td><br /><input  class="btn btn-info" style="color:darkgoldenrod;background-color:white;" value="Submit" id="btnSubmit" onclick="location.href='@Url.Action("Index", "UnderProcess")'"></td>
    </tr>

</table>

Hackathon/Views/MentalHealthAssesment/SleepDisorderAssesment.cshtml
@{
    ViewData["Title"] = "SleepDisorderAssesment";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1 style="color:darkgoldenrod">Sleep Disorder Assesment</h1>
<table style="color:darkgoldenrod">
    <tr>
        <td>How are your sleeping habits over past few months ?</td>
    </tr>
    <tr>
        <td>< 4 Hours @Html.RadioButton("SleepingHabbits", "lessthanfourhours")&nbsp;&nbsp;&nbsp;&nbsp; 4 - 6 hours @Html.RadioButton("SleepingHabbits", "fourtosixhours")&nbsp;&nbsp;&nbsp;&nbsp; 6 -8 hours @Html.RadioButton("SleepingHabbits", "sixtoeighthours")&nbsp;&nbsp;&nbsp;&nbsp;> 8 Hours @Html.RadioButton("SleepingHabbits", "greaterthaneighthours")&nbsp;&nbsp;&nbsp;&nbsp;</td> 
    </tr>
    <tr>
        <td>Have you noticed any changes..?</td>
        <td>Difficulty Sleeping @Html.RadioButton("SleepingChanges", "difficultysleeping")&nbsp;&nbsp;&nbsp;&nbsp;Restlessness @Html.RadioButton("SleepingChanges", "restlessness")&nbsp;&nbsp;&nbsp;&nbsp;</td>
    </tr>
    <tr>
        <td>How was the quality of sleep?</td>      
    </tr>
    <tr>
        <td>Tired When You Get Up @Html.RadioButton("SleepingQuality", "tired")&nbsp;&nbsp;&nbsp;&nbsp; Feel Fresh and Active @Html.RadioButton("SleepingQuality", "fresh")&nbsp;&nbsp;&nbsp;&nbsp;</td>
    </tr>
    <tr>
        <td>Appetite over the past few weeks..?  </td>
    </tr>
    <tr>
        <td>
         Good @Html.RadioButton("Apetite", "Good")&nbsp;&nbsp;&nbsp;&nbsp;Average @Html.RadioButton("Apetite", "Average")&nbsp;&nbsp;&nbsp;&nbsp;Poor @Html.RadioButton("Apetite", "Poor")&nbsp;&nbsp;&nbsp;&nbsp;
        </td>
    </tr>
    <tr>
        <td>Have your eating habits altered in any way..?</td>
    </tr>
    <tr>
        <td>Yes @Html.RadioButton("EatingHabbitsAltered", "Yes")&nbsp;&nbsp;&nbsp;&nbsp;No @Html.RadioButton("EatingHabbitsAltered", "No")&nbsp;&nbsp;&nbsp;&nbsp;</td>
    </tr>
    <tr>
        <td> <input  class="btn btn-info" style="color:darkgoldenrod;background-color:white;" value="Submit" id="btnSubmit"  onclick="location.href='@Url.Action("Index", "UnderProcess")'"></td>
    </tr>
</table>
                                                             
                                                         

Hackathon/Views/MentalHealthAssesment/StressAssesment.cshtml
@{
    ViewData["Title"] = "StressAssesment";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1   style="color:darkgoldenrod">Stress Assesment</h1>
<table style="color:darkgoldenrod">
    <tr>
        <td>Do you at times feel nervous? </td>
    </tr>
    <tr>
        <td> Yes @Html.RadioButton("nervous", "Yes")&nbsp;&nbsp;&nbsp;&nbsp; No @Html.RadioButton("nervous", "No")&nbsp;&nbsp;&nbsp;&nbsp;</td>
    </tr>
    <tr>
        <td>Do you at times feel frustrated? </td>
    </tr>
    <tr>
        <td>Yes @Html.RadioButton("frustated", "Yes")&nbsp;&nbsp;&nbsp;&nbsp; No @Html.RadioButton("frustated", "No")&nbsp;&nbsp;&nbsp;&nbsp;</td>
    </tr>
    <tr>
        <td>Are you insomniac?  </td>
    </tr>
    <tr>
        <td>Yes @Html.RadioButton("insomaniac", "Yes")&nbsp;&nbsp;&nbsp;&nbsp; No @Html.RadioButton("insomaniac", "No")&nbsp;&nbsp;&nbsp;&nbsp;</td>
    </tr>
    <tr>
        <td>Do you feel low on energy? </td>
    </tr>
    <tr>
        <td>Yes @Html.RadioButton("energy", "Yes")&nbsp;&nbsp;&nbsp;&nbsp; No @Html.RadioButton("energy", "No")&nbsp;&nbsp;&nbsp;&nbsp;</td>
    </tr>
    <tr>
        <td>Do you have severe headaches recently which comes back after medication?</td>
    </tr>
    <tr>
        <td>
            Yes @Html.RadioButton("headache", "Yes")&nbsp;&nbsp;&nbsp;&nbsp; No @Html.RadioButton("headache", "No")&nbsp;&nbsp;&nbsp;&nbsp;
        </td>
    </tr>
    <tr>
        <td>Do you know what led to this emotion?</td>
    </tr>
    <tr>
        <td>Yes @Html.RadioButton("emotiontrigger", "Yes")&nbsp;&nbsp;&nbsp;&nbsp; No @Html.RadioButton("emotiontrigger", "No")&nbsp;&nbsp;&nbsp;&nbsp;</td>
    </tr>
    <tr>
        <td>If Yes. Is it result of a recent activity?</td>
    </tr>
    <tr>
        <td>Yes @Html.RadioButton("recent", "Yes")&nbsp;&nbsp;&nbsp;&nbsp; No @Html.RadioButton("recent", "No")&nbsp;&nbsp;&nbsp;&nbsp;</td>
    </tr>
    <tr>
        <td>How recent was that event?</td>
    </tr>
    <tr>
        <td>1-2 days back  @Html.RadioButton("howrecent", "days")&nbsp;&nbsp;&nbsp;&nbsp; A week back @Html.RadioButton("howrecent", "weeks")&nbsp;&nbsp;&nbsp;&nbsp; A couple of months back @Html.RadioButton("howrecent", "months")&nbsp;&nbsp;&nbsp;&nbsp;</td>
    </tr>
    <tr>
        <td>
            <input  class="btn btn-info" style="color:darkgoldenrod;background-color:white;" value="Submit" id="btnSubmit"  onclick="location.href='@Url.Action("Index", "UnderProcess")'">
        </td>
    </tr>
</table>